apiVersion: v1
kind: "List"
items:
- apiVersion: extensions/v1beta1
  kind: Deployment
  metadata:
    name: azure-spring-boot-sample
  spec:
    replicas: 2
    template:
      metadata:
        labels:
          app: azure-spring-boot-sample
      spec:
        containers:
        - name: azure-spring-boot-sample
          image: ${ACR_SERVER}/azure-spring-boot-sample:${BUILD_NUMBER}
          ports:
          - containerPort: 8080
        imagePullSecrets:
        - name: ${KUBERNETES_SECRET_NAME}
- apiVersion: v1
  kind: Service
  metadata:
    name: azure-spring-boot-sample
  spec:
    type: LoadBalancer
    selector:
      app: azure-spring-boot-sample
    ports:
    - port: 80
      targetPort: 8080
